import type { Metadata } from "next";
import Link from "next/link";
import { BadgeCheck, Ban, CircleDollarSign, Filter, Layers, MinusCircle, ShoppingCart, TrendingUp, Users, XCircle } from "lucide-react";
import { KpiCard } from "@/components/hc4m/KpiCard";
import { SectionCard } from "@/components/hc4m/SectionCard";
import { AcceptanceByBuyerChart, BidComparisonChart, FunnelChart, OutcomeBreakdownChart, ReasonBreakdownChart, RevenueByBuyerChart } from "@/components/hc4m/charts";
import { StatusBadge } from "@/components/hc4m/StatusBadge";
import { LeadTable } from "@/components/hc4m/LeadTable";
import { allBuyerSummaries, currency, funnelSteps, overviewKpis, percent, reasonBreakdown, statusBreakdown } from "@/lib/hc4m/metrics";
import { buyerSlug, loadDataset } from "@/lib/hc4m/source";
import { BUYER_STATUSES } from "@/lib/hc4m/types";

export const metadata: Metadata = {
  title: "Buyer Insights Overview",
  description: "See how every connected buyer responded to HC4M leads: acceptances, outbids, rejections, bids and revenue at a glance.",
};

export default function Overview() {
  const { campaign, attempts } = loadDataset();
  const kpi = overviewKpis();
  const buyers = allBuyerSummaries();
  return (
    <main className="mx-auto max-w-[104rem] space-y-6 px-5 py-7">
      <div className="flex flex-wrap items-end justify-between gap-3">
        <div>
          <h1 className="font-display text-2xl font-bold">Buyer Insights Overview</h1>
          <p className="mt-1 text-sm text-muted-foreground">{campaign.name} · {campaign.date} · {kpi.totalLeads} leads, {kpi.totalAttempts} buyer responses</p>
        </div>
        <div className="flex flex-wrap gap-2">{BUYER_STATUSES.map((s) => <StatusBadge key={s} status={s} />)}</div>
      </div>

      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5">
        <KpiCard label="Total leads" value={kpi.totalLeads} Icon={Layers} />
        <KpiCard label="Leads sold" value={kpi.leadsSold} sub={`${percent(kpi.leadsSold / kpi.totalLeads)} of leads sold`} Icon={ShoppingCart} tone="success" />
        <KpiCard label="Total buyer attempts" value={kpi.totalAttempts} sub="Every buyer evaluation" Icon={Users} />
        <KpiCard label="Buyer acceptances" value={kpi.accepted} Icon={BadgeCheck} tone="success" hint="A buyer actually purchased the lead" />
        <KpiCard label="Outbid attempts" value={kpi.outbid} Icon={Ban} tone="info" hint="Buyer qualified or bid, another buyer won" />
        <KpiCard label="Rejected attempts" value={kpi.rejected} Icon={XCircle} tone="danger" />
        <KpiCard label="Filtered-out attempts" value={kpi.filteredOut} Icon={Filter} tone="warning" />
        <KpiCard label="Not accepted" value={kpi.notAccepted} Icon={MinusCircle} tone="muted" />
        <KpiCard label="Total revenue" value={currency(kpi.totalRevenue)} Icon={CircleDollarSign} tone="success" />
        <KpiCard label="Avg winning price" value={currency(kpi.avgWinningPrice)} Icon={TrendingUp} />
      </div>

      <div className="grid gap-6 xl:grid-cols-2">
        <SectionCard title="Buyer acceptance by buyer" description="How many leads each buyer actually purchased."><AcceptanceByBuyerChart data={buyers} /></SectionCard>
        <SectionCard title="Buyer outcome breakdown" description="Accepted, outbid, rejected, filtered out or not accepted."><OutcomeBreakdownChart data={statusBreakdown()} /></SectionCard>
        <SectionCard title="Buyer bid comparison" description="Which buyers bid most competitively."><BidComparisonChart data={buyers} /></SectionCard>
        <SectionCard title="Revenue by buyer" description="Total purchase value generated by each buyer."><RevenueByBuyerChart data={buyers} /></SectionCard>
        <SectionCard title="Lead outcome funnel" description="From lead received all the way to a buyer acceptance."><FunnelChart data={funnelSteps()} /></SectionCard>
        <SectionCard title="Rejection & filter reasons" description="Why buyers did not receive or accept leads."><ReasonBreakdownChart data={reasonBreakdown()} /></SectionCard>
      </div>

      <SectionCard title="Buyer scoreboard" description="Click a buyer for their full activity and summary.">
        <div className="overflow-x-auto">
          <table className="w-full min-w-[54rem] text-sm">
            <thead><tr className="text-left text-xs font-semibold uppercase tracking-wide text-muted-foreground"><th className="pb-2 pr-4">Buyer</th><th className="pb-2 pr-4 text-right">Evaluated</th><th className="pb-2 pr-4 text-right">Accepted</th><th className="pb-2 pr-4 text-right">Acceptance rate</th><th className="pb-2 pr-4 text-right">Avg bid</th><th className="pb-2 pr-4 text-right">Highest bid</th><th className="pb-2 text-right">Purchase value</th></tr></thead>
            <tbody>{buyers.map((b) => <tr key={b.buyer} className="border-t border-border"><td className="py-2.5 pr-4"><Link href={`/buyers/${buyerSlug(b.buyer)}`} className="font-medium text-info hover:underline">{b.buyer}</Link></td><td className="py-2.5 pr-4 text-right tabular-nums">{b.evaluated}</td><td className="py-2.5 pr-4 text-right tabular-nums">{b.accepted}</td><td className="py-2.5 pr-4 text-right tabular-nums">{percent(b.acceptanceRate)}</td><td className="py-2.5 pr-4 text-right tabular-nums">{currency(b.avgBid)}</td><td className="py-2.5 pr-4 text-right tabular-nums">{currency(b.highestBid)}</td><td className="py-2.5 text-right font-medium tabular-nums">{currency(b.totalValue)}</td></tr>)}</tbody>
          </table>
        </div>
      </SectionCard>
      <LeadTable attempts={attempts} />
    </main>
  );
}
